### PR TITLE
Updated UI and data flow for new squad creation

### PR DESCRIPTION
**Pull request by manolingam**
* Updated the data flow for new squad creation.
* Implemented smooth scroll for the UI.

### CODE REVIEW

**Review by luisivan — CHANGES_REQUESTED** [review]
This is great! Love the scrolling.

Can we rename the `telegram` variable to `inviteLink`? Those links may even be WhatsApp/WeChat/etc. in the future.

Also, we should automatically save the DAO address, so we don't need a text field for that.
Basically it would work this way:
1. User registers with Fortmatic, we ask them to buy ETH
2. User clicks *Launch help squad*, and we ask them to sign an Ethereum transaction with Fortmatic to deploy a new DAO
3. We will check the transaction on Ethereum, and once the DAO is deployed, save its address in a variable. Once we have that, we send a POST to the server with all the variables (name, desc, inviteLink and daoAddress).

Sounds good?

**Review by w0xter — APPROVED** [review]
### The new buttons are very cool!! :fire: :fire:
I prefer the new workflow, maybe is a good idea to put a home button to return to the home page, just a simple :house: icon with the main color of helpDAO.

**Comment by manolingam** [comment]
Thanks @luisivan and @w0xter for the review. 

* Removed _DAO Address Text field_ in the form.
* Removed all temporary variables to use states hereafter.
* Added a Home button for navigating back to the Home Page.

Also, am not sure about the Fortmatic registration. Will discuss about it in discord.

**Review by luisivan — APPROVED** [review]
Ready! Great job

**Pull request merged**
