### PR TITLE
Added Fortmatic

### PR DESCRIPTION
**Pull request by luisivan**
- Adds [`use-wallet`](https://github.com/aragon/use-wallet) for [Fortmatic](https://fortmatic.com) integration.
- Adds new route `/new/register` so that people can register using Fortmatic.

The idea is that after entering the name, description and invite link for their help squad, users will register with Fortmatic, buy some ETH with their credit card and launch a DAO.

We can save the name, description and invite link in localStorage, and once the user has created the DAO, the DAO address too. Once the user clicks the final button to deploy the help squad, we can send it all to the backend.

### CODE REVIEW

**Review by w0xter — APPROVED** [review]
## Review:

### Warnings:

- **npm** warn me about  some vulnerabilities:

  ```
                                                                                  
                         === npm audit security report ===                        
                                                                                  
  ┌──────────────────────────────────────────────────────────────────────────────┐
  │                                Manual Review                                 │
  │            Some vulnerabilities require your attention to resolve            │
  │                                                                              │
  │         Visit https://go.npm.me/audit-guide for additional guidance          │
  └──────────────────────────────────────────────────────────────────────────────┘
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ Low           │ Insecure Credential Storage                                  │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ web3                                                         │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Patched in    │ No patch available                                           │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ use-wallet                                                   │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ use-wallet > @web3-react/torus-connector >                   │
  │               │ @toruslabs/torus-embed > web3                                │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/877                             │
  └───────────────┴──────────────────────────────────────────────────────────────┘
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ Moderate      │ Regular Expression Denial of Service                         │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ acorn                                                        │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Patched in    │ >=5.7.4 <6.0.0 || >=6.4.1 <7.0.0 || >=7.1.1                  │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ use-wallet                                                   │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ use-wallet > @web3-react/torus-connector >                   │
  │               │ @toruslabs/torus-embed > @toruslabs/torus.js > eccrypto >    │
  │               │ acorn                                                        │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/1488                            │
  └───────────────┴──────────────────────────────────────────────────────────────┘
  ```

- Also the **linter** warn me about some vars that were never used:

  ```
  ./src/squads/Register.js
    Line 1:16:  'useState' is defined but never used            no-unused-vars
    Line 3:8:   'TextField' is defined but never used           no-unused-vars
    Line 8:7:   'useStyles' is assigned a value but never used  no-unused-vars
  
  ./src/App.js
    Line 1:17:  'useState' is defined but never used  no-unused-vars
  ```

### Improvements:

- Maybe some form check before send it, to ensure that the data is correct, like the ***invite link*** starts with **t.me/**  or the ***daoAddress*** is an **hexadecimal number**.
- Make all the buttons clickable not only the text inside the button, is a bit confusing.

### Conclusions:

For me the review is approved, we can make issues with the improvements and post it on the board, they are very simple to complete. About the vulnerabilities maybe we can downgrade the module to a version without errors.

**Thanks!**

**Comment by manolingam** [comment]
***Review***

Fortmatic integation works good. As @w0xter mentioned, there were some minor issues which I fixed it in this [pull request](https://github.com/helpdao/donation-portal/pull/6). 

Moreover, is fortmatic registration required for squads which don't have a DAO? If so, I integrated the registration within the form for easier navigation in the above mentioned pull request.

**Review by manolingam — CHANGES_REQUESTED** [review]
Approved.

**Review by manolingam — APPROVED** [review]

**Comment by manolingam** [comment]
Merged this pull request for the next one to be checked for conflicts.

**Pull request merged**
